# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56ae12a9fa557fb448cdc2a74194de17f078a3f3d3cc5075415b453662cc0f40372493311a5b48f4f3e3da4ed1132402c670597fa9e684892508950d48689ae7

test:
  secret_key_base: eacdbe3071b36bbc06deeea7e67f60fe057e12348552e7161db84a2aa0ba770d707888e017b32513858a5b97fcfbbb921d53e28814271242d6b6c9b0ecf2d2a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
